//React
// ライブラリ
import Store from 'electron-store';
//スタイル群
//コンポーネント
//マテリアルUI
//マテリアルUI Icon


export default  function Languages(key)  {


    const store_audio_control = new Store({name: 'store_audio_control'})    // 早送り巻き戻し管理ストア
    const locale = store_audio_control.get('LANG')
    // 翻訳コードの一覧配列
    const locale_lists = [
        "ja","en","it","et",
        "nl","el","sv","es",
        "sk","sl","cs","da",
        "de","hu","fi","fr",
        "bg","pl","pt","lv",
        "lt","ro","ru","zh"
    ]
    // console.log(locale)


    // Done: 画面配置を初期化しました。
    // not work: 情報を読み込み中です。
    // Done: 多言語対応化
    // PlayBack Rate Contorl Media Player
    // BaRaCoa

    // Translate Work Todo
    // ToDp:Speed -> Rate
    // TOdo:VolUp
    // TOdo:VolDown


    // 翻訳用のテキスト
    const trans = {
        ja: {
            Patron:'パトロン',
            Patron_message_ON:'メッセージを表示',
            Rewind: '巻き戻し',
            Forward: '早送り',
            Mini: 'ミニプレイヤー ',
            SwitchColumn_2: '２列に切り替え',
            SwitchColumn_1: '１列に切り替え',
            RestoreWindow: 'プレイヤー',
            Previous: '戻る',
            Next: '進む',
            PBR_Reduce: '再生速度を減らす',
            PBR_Set_1: '登録した再生速度１にする',
            PBR_Set_2: '登録した再生速度２にする',
            PBR_Add: '再生速度を増やす',
            Reset: 'リセット',
            Pause: '一時停止',
            Play: '再生',
            Shuffle: 'シャッフル',
            Repeat: 'リピート',
            Mute: 'ミュート ',
            Fold: '折りたたむ',
            Extend: '展開',
            Title: 'タイトル',
            Count: '再生回数',
            PlaybackTime: '再生時間',
            Date: '最終再生日',
            Edlapsed: '経過日数',
            OpenMedia: 'Open Media',
            Setting: '設定',
            Lang: '言語',
            PBR: '再生速度',
            Vol: '音量',
            VolUp: '上げる',
            VolDown: '下げる',
            Time: '時間操作',
            SetLang: '言語設定',
            UseLang: '使用言語',
            SetPBR_Set1: '再生速度１を登録する',
            SetPBR_Set2: '再生速度２を登録する',
            SetPBR_def: '再生速度の初期値',
            SetPBR_step: '再生速度の刻み',
            SetPBR_max: '再生速度の最大値',
            SetPBR_min: '再生速度の最小値',
            SetVol: '音量の設定',
            SetRewind_L: '巻き戻し（大）',
            SetRewind_S: '巻き戻し（小）',
            SetForward_S: '早送り（小）',
            SetForward_L: '早送り（大）',
            MediaPlayer: 'メディアプレイヤー',
            History: '履歴',
            Setting: '設定',
            OpenMedia: 'Open Media',
            Clear: 'クリア',
            Reload: 'リロード',
            DnD_Here: 'ここにメディアをドラッグ＆ドロップします',
            Favorite: 'お気に入り',
            Delete: '削除',
            FullScreen: '全画面',
            Hide: '非表示',
            Delete_Dia_title:'トラック情報を削除',
            Delete_Dia_info:'本当に削除してもよろしいですか？削除したトラック情報は復元できません。',
            OK:'はい',
            Cancel:'キャンセル',
            Init_history:'初期化',
            Del_history: '履歴の全削除',
            Del_history_btn: '履歴を初期化する',
            Del_history_dia:'本当に削除してもよろしいですか？削除した履歴は復元できません。',
            Del_history_dia2:'削除後に画面を再起動します。',
            boot_count_01:'1回目の起動: 意識の高い学習者で在らせられる、購入者さま。こんにちは。ご購入ありがとうございます😊 ',
            boot_count_10:'10回目の起動: アプリの使用感はいかがですか。欲しい機能がありましたら、TwitterへDMよろしくおねがします😊  改善の助けになります。ありがとう。',
            boot_count_50:'50回目の起動: アプリを気に入っていだだけましたら、App Storeにて星5つのレビューをお願い致します。レビューでの応援も励みになります😊 ありがとう。',
            boot_count_100:'100回目の起動: 🎉 おめでとうございます。あなたはこのアプリを100回起動しました。あなたにより良い学習環境と、学び得た知識を用いて人類に貢献する機械が訪れることが在らんことを。ありがとう。',
        },
        en: {
            Patron_message_ON: 'Show message',
            Patron:'Patron',
            Rewind: 'Rewind',
            Forward: 'Forward',
            Mini: 'Mini Player ',
            SwitchColumn_2: 'Switch to 2 columns',
            SwitchColumn_1: 'Switch to 1 column',
            RestoreWindow: 'Restore Window',
            Previous: 'Previous',
            Next: 'Next',
            PBR: 'Playback Rate',
            PBR_Reduce: 'Reduce Playback Rate',
            PBR_Set_1: 'Set to Playback Rate 1',
            PBR_Set_2: 'Set to Playback Rate 2',
            PBR_Add: 'Increase Playback Rate',
            VolUp: 'Up',
            VolDown: 'Down',
            Reset: 'Reset',
            Pause: 'Pause',
            Play: 'Play',
            Shuffle: 'Shuffle',
            Repeat: 'Repeat',
            Mute: 'Mute ',
            Fold: 'Fold',
            Extend: 'Extend',
            Title: 'Title',
            Count: 'Count',
            PlaybackTime: 'Playback time',
            Date: 'Last played day',
            Edlapsed: 'Elapsed days',
            OpenMedia: 'Open Media',
            Setting: 'Setting',
            Lang: 'Language',
            Vol: 'Volume',
            Time: 'Time control',
            SetLang: 'Language setting',
            UseLang: 'Use Language',
            SetPBR_Set1: 'Register Playback Rate 1',
            SetPBR_Set2: 'Register Playback Rate 2',
            SetPBR_def: 'Initial value of Playback Rate',
            SetPBR_step: 'Playback Rate increments',
            SetPBR_max: 'Maximum Playback Rate',
            SetPBR_min: 'Minimum Playback Rate',
            SetVol: 'Set volume',
            SetRewind_L: 'Rewind (large)',
            SetRewind_S: 'Rewind (small)',
            SetForward_S: 'Fast Forward (small)',
            SetForward_L: 'Fast Forward (Large)',
            MediaPlayer: 'Media Player',
            History: 'History',
            Setting: 'Setting',
            OpenMedia: 'Open Media',
            Clear: 'Clear',
            Reload: 'Reload',
            DnD_Here: 'Drag and drop media here',
            Favorite: 'Favorite',
            Delete: 'Delete',
            FullScreen: 'FullScreen',
            Hide: 'Hide',
            Delete_Dia_title:'Delete track information',
            Delete_Dia_info:'Are you sure you want to delete it? Deleted track information cannot be restored.',
            OK:'OK',
            Cancel:'Cancel',
            Init_history:'初期化',
            Del_history: '学習履歴の全削除',
            Del_history_btn: '学習履歴を初期化する',
            Del_history_dia:'本当に削除してもよろしいですか？初期化した履歴は復元できません。',
            Del_history_dia2:'削除後に画面を再起動します。',
            Review_ask:'こんにちは、しばらくの間 EWWW Image Optimizer をご使用いただいておりますが、お役に立てていれば幸いです。',
            Review_ask:'WordPress.org で評価していただくことで、プラグイン改善の助けになります。ありがとうございます。',
        },
        it: {
            VolUp: 'Su',
            VolDown: 'Giù',
            PlaybackTime: 'Tempo di riproduzione',
            Patron_message_ON: 'Mostra il messaggio',
            Patron:'Patron',
            Rewind:"Riavvolgere",
            Forward :"Avanti",
            Mini :"Mini lettore",
            SwitchColumn_2 :"Passa a 2 colonne",
            SwitchColumn_1 :"Passa a 1 colonna",
            RestoreWindow :"Ripristina finestra",
            Previous :"Precedente",
            Next :"Successivo",
            PBR_Reduce :"Riduci la velocità di riproduzione",
            PBR_Set_1 :"Imposta la velocità di riproduzione 1",
            PBR_Set_2 :"Imposta la velocità di riproduzione 2",
            PBR_Add :"Aumenta la velocità di riproduzione",
            Reset :"Azzerare",
            Pause :"Mettere in pausa",
            Play :"Riproduci",
            Shuffle :"Shuffle",
            Repeat :"Ripeti",
            Mute :"Muto",
            Fold :"Piegare",
            Extend :"Estendere",
            Title :"Titolo",
            Count :"Conta",
            Date :"Ultimo giorno giocato",
            Edlapsed :"Giorni trascorsi",
            OpenMedia :"Aprire i media",
            Setting :"Impostazione",
            Lang :"Lingua",
            PBR :"Velocità di riproduzione",
            Vol :"Volume",
            Time :"Controllo del tempo",
            SetLang :"Impostazione della lingua",
            UseLang :"Utilizzare la lingua",
            SetPBR_Set1 :"Registra la velocità di riproduzione 1",
            SetPBR_Set2 :"Registra la velocità di riproduzione 2",
            SetPBR_def :"Valore iniziale della velocità di riproduzione",
            SetPBR_step :"Incrementi della velocità di riproduzione",
            SetPBR_max :"Velocità massima di riproduzione",
            SetPBR_min :"Velocità minima di riproduzione",
            SetVol :"Imposta il volume",
            SetRewind_L :"Riavvolgimento (grande)",
            SetRewind_S :"Riavvolgimento (piccolo)",
            SetForward_S :"Avanti veloce (piccolo)",
            SetForward_L :"Avanti veloce (grande)",
            MediaPlayer :"Lettore multimediale",
            History :"Storia",
            Setting :"Impostazione",
            OpenMedia :"Aprire i media",
            Clear :"Cancella",
            Reload :"Ricarica",
            DnD_Here :"Trascinare e rilasciare i media qui",
            Favorite :"Preferito",
            Delete :"Cancella",
            FullScreen :"Schermo intero",
            Hide :"Nascondi",
            Delete_Dia_title:'Cancellare le informazioni sulla traccia',
            Delete_Dia_info:'Sei sicuro di volerle cancellare? Le informazioni sulla traccia cancellata non possono essere ripristinate.',
            OK:'Sì',
            Cancel:'Annulla',
        },
        et: {
            VolUp: 'Üles',
            VolDown: 'Alla',
            PlaybackTime: 'Taasesitusaeg',
            Patron_message_ON: 'Näita sõnumit',
            Patron:'Patroon',
            Rewind:"Rewind",
            Forward :"Edasi",
            Mini :"Mini mängija",
            SwitchColumn_2 :"Üleminek 2 veerule",
            SwitchColumn_1 :"Üleminek 1 veerule",
            RestoreWindow :"Akna taastamine",
            Previous :"Eelmine",
            Next :"Järgmine",
            PBR_Reduce :"Vähendage taasesituse kiirust",
            PBR_Set_1 :"Seadistage taasesituskiirus 1",
            PBR_Set_2 :"Seadistage taasesituskiirus 2",
            PBR_Add :"Suurendada taasesituskiirust",
            Reset :"Nullida",
            Pause :"Peatus",
            Play :"Mängi",
            Shuffle :"Segamine",
            Repeat :"Kordus",
            Mute :"Mute",
            Fold :"Fold",
            Extend :"Extend",
            Title :"Pealkiri",
            Count :"Count",
            Date :"Viimati mängitud päev",
            Edlapsed :"Kulunud päevad",
            OpenMedia :"Avatud meedia",
            Setting :"Seadistamine",
            Lang :"Keel",
            PBR :"Taasesituskiirus'",
            Vol :"Helitugevus",
            Time :"Aja juhtimine",
            SetLang :"Keele seadistus",
            UseLang :"Keele kasutamine",
            SetPBR_Set1 :"Registreeri taasesituskiirus 1",
            SetPBR_Set2 :"Registreeri taasesituskiirus 2",
            SetPBR_def :"Taasesituskiiruse algväärtus",
            SetPBR_step :"Taasesituskiiruse suurendamine",
            SetPBR_max :"Maksimaalne taasesituskiirus",
            SetPBR_min :"Minimaalne taasesituskiirus",
            SetVol :"Helitugevuse seadistamine",
            SetRewind_L :"Tagasi kerimine (suur",
            SetRewind_S :"Tagasi kerimine (väike)",
            SetForward_S :"Kiiresti edasi (väike)",
            SetForward_L :"Kiire edasi (suur)",
            MediaPlayer :"Meediamängija",
            History :"Ajalugu",
            Setting :"Seadistamine",
            OpenMedia :"Avatud meedia",
            Clear :"Tühjenda",
            Reload :"Reload",
            DnD_Here :"Lohistage meedia siia",
            Favorite :"Lemmik",
            Delete :"Kustuta",
            FullScreen :"FullScreen",
            Hide :"Peida",
            Delete_Dia_title:'Kustuta teekonnateave',
            Delete_Dia_info:'Kas olete kindel, et soovite seda kustutada? Kustutatud rööbasteavet ei saa taastada.',
            OK:'Jah',
            Cancel:'Tühista',
        },
        nl: {
            VolUp: 'Omhoog',
            VolDown: 'Omlaag',
            PlaybackTime: 'Afspeeltijd',
            Patron_message_ON: 'Toon bericht',
            Patron:'Beschermheer',
            Rewind:"Terugspoelen",
            Forward :"Vooruit",
            Mini :"Minispeler",
            SwitchColumn_2 :"Omschakelen naar 2 kolommen",
            SwitchColumn_1 :"Wisselen naar 1 kolom",
            RestoreWindow :"Herstel Venster",
            Previous :"Vorige",
            Next :"Volgende",
            PBR_Reduce :"Verminder afspeelsnelheid",
            PBR_Set_1 :"Stel afspeelsnelheid 1 in",
            PBR_Set_2 :"Stel afspeelsnelheid 2 in",
            PBR_Add :"Verhoog afspeelsnelheid",
            Reset :"Reset",
            Pause :"Pauze",
            Play :"Afspelen",
            Shuffle :"Shuffle",
            Repeat :"Herhalen",
            Mute :"Mute",
            Fold :"Vouwen",
            Extend :"Uitbreiden",
            Title :"Titel",
            Count :"Tel",
            Date :"Laatst gespeelde dag",
            Edlapsed :"Verstreken dagen",
            OpenMedia :"Media openen",
            Setting :"Instellen",
            Lang :"Taal",
            PBR :"Afspeelsnelheid",
            Vol :"Volume",
            Time :"Tijdinstelling",
            SetLang :"Taal instellen",
            UseLang :"Taal gebruiken",
            SetPBR_Set1 :"Afspeelsnelheid 1 registreren",
            SetPBR_Set2 :"Afspeelsnelheid 2 registreren",
            SetPBR_def :"Initiële waarde van afspeelsnelheid",
            SetPBR_step :"Stapsgewijze weergave snelheid",
            SetPBR_max :"Maximale afspeelsnelheid",
            SetPBR_min :"Minimale afspeelsnelheid",
            SetVol :"Volume instellen",
            SetRewind_L :"Terugspoelen (groot",
            SetRewind_S :"Terugspoelen (klein)",
            SetForward_S :"Snel vooruitspoelen (klein)",
            SetForward_L :"Snel vooruit (groot)",
            MediaPlayer :"Media Speler",
            History :"Geschiedenis",
            Setting :"Instellen",
            OpenMedia :"Media openen",
            Clear :"Wissen",
            Reload :"Herladen",
            DnD_Here :"Media hierheen slepen",
            Favorite :"Favoriet",
            Delete :"Verwijderen",
            FullScreen :"Volledig scherm",
            Hide :"Verberg",
            Delete_Dia_title:'Nummerinformatie verwijderen',
            Delete_Dia_info:'Weet u zeker dat u het wilt verwijderen? Gewiste trackinformatie kan niet worden hersteld.',
            OK:'Ja',
            Cancel:'Annuleren',
        },
        el: {
            VolUp: 'Πάνω',
            VolDown: 'Κάτω',
            PlaybackTime: 'Χρόνος αναπαραγωγής',
            Patron_message_ON: 'Εμφάνιση μηνύματος',
            Patron:'Προστάτης',
            Rewind:"Αναδίπλωση ",
            Forward :"Εμπρός ",
            Mini :"Mini Player ",
            SwitchColumn_2 :"Εναλλαγή σε 2 στήλες ",
            SwitchColumn_1 :"Εναλλαγή σε 1 στήλη ",
            RestoreWindow :"Επαναφορά παραθύρου ",
            Previous :"Προηγούμενο ",
            Next :"Επόμενο ",
            PBR_Reduce :"Μείωση της ταχύτητας αναπαραγωγής ",
            PBR_Set_1 :"Ρύθμιση στην ταχύτητα αναπαραγωγής 1 ",
            PBR_Set_2 :"Ορισμός ταχύτητας αναπαραγωγής 2 ",
            PBR_Add :"Αύξηση της ταχύτητας αναπαραγωγής ",
            Reset :"Επαναφορά ",
            Pause :"Παύση ",
            Play :"Αναπαραγωγή ",
            Shuffle :"Τυχαία αναπαραγωγή ",
            Repeat :"Επανάληψη ",
            Mute :"Σίγαση ",
            Fold :"Αναδίπλωση ",
            Extend :"Επέκταση ",
            Title :"Τίτλος ",
            Count :"Count ",
            Date :"Τελευταία ημέρα αναπαραγωγής ",
            Edlapsed :"Ημέρες που έχουν παρέλθει ",
            OpenMedia :"Άνοιγμα πολυμέσων ",
            Setting :"Ρύθμιση ",
            Lang :"Γλώσσα ",
            PBR :"Ταχύτητα αναπαραγωγής' ",
            Vol :"Ένταση ήχου ",
            Time :"Έλεγχος χρόνου ",
            SetLang :"Ρύθμιση γλώσσας ",
            UseLang :"Χρήση γλώσσας ",
            SetPBR_Set1 :"Εγγραφή ταχύτητας αναπαραγωγής 1 ",
            SetPBR_Set2 :"Εγγραφή ταχύτητας αναπαραγωγής 2 ",
            SetPBR_def :"Αρχική τιμή της ταχύτητας αναπαραγωγής ",
            SetPBR_step :"Αυξήσεις ταχύτητας αναπαραγωγής ",
            SetPBR_max :"Μέγιστη ταχύτητα αναπαραγωγής ",
            SetPBR_min :"Ελάχιστη ταχύτητα αναπαραγωγής ",
            SetVol :"Ρύθμιση έντασης ήχου ",
            SetRewind_L :"Αντίστροφη κύλιση (μεγάλη ",
            SetRewind_S :"Αντίστροφη κύλιση (μικρή) ",
            SetForward_S :"Γρήγορη προώθηση προς τα εμπρός (μικρό) ",
            SetForward_L :"Γρήγορη προώθηση (μεγάλη) ",
            MediaPlayer :"Media Player ",
            History :"Ιστορία ",
            Setting :"Ρύθμιση ",
            OpenMedia :"Άνοιγμα πολυμέσων ",
            Clear :"Εκκαθάριση ",
            Reload :"Επαναφόρτωση ",
            DnD_Here :"Σύρετε και αφήστε τα μέσα εδώ ",
            Favorite :"Αγαπημένο ",
            Delete :"Διαγραφή ",
            FullScreen :"Πλήρης οθόνη ",
            Hide :"Απόκρυψη ",
            Delete_Dia_title:'Διαγραφή πληροφοριών κομματιού',
            Delete_Dia_info:'Είστε σίγουροι ότι θέλετε να το διαγράψετε; Οι διαγραμμένες πληροφορίες κομματιών δεν μπορούν να επαναφερθούν.',
            OK:'Ναι',
            Cancel:'Ακύρωση',
        },
        sv: {
            VolUp: 'Upp',
            VolDown: 'Ner',
            PlaybackTime: 'Uppspelningstid',
            Patron_message_ON: 'Visa meddelande',
            Patron:'Beskyddare',
            Rewind:"Spola tillbaka ",
            Forward :"Framåt ",
            Mini :"Minispelare ",
            SwitchColumn_2 :"Växla till 2 kolumner ",
            SwitchColumn_1 :"Växla till 1 kolumn ",
            RestoreWindow :"Återställ fönstret ",
            Previous :"Föregående ",
            Next :"Nästa ",
            PBR_Reduce :"Minska uppspelningshastigheten ",
            PBR_Set_1 :"Ställ in uppspelningshastighet 1 ",
            PBR_Set_2 :"Ställ in uppspelningshastighet 2 ",
            PBR_Add :"Öka uppspelningshastigheten ",
            Reset :"Återställ ",
            Pause :"Pausa ",
            Play :"Uppspelning ",
            Shuffle :"Shuffle ",
            Repeat :"Upprepa ",
            Mute :"Mute ",
            Fold :"Vik ",
            Extend :"Utöka ",
            Title :"Titel ",
            Count :"Count ",
            Date :"Senast spelade dag ",
            Edlapsed :"Förbrukade dagar ",
            OpenMedia :"Öppna media ",
            Setting :"Inställning av ",
            Lang :"Språk ",
            PBR :"Uppspelningshastighet' ",
            Vol :"Volym ",
            Time :"Tidskontroll ",
            SetLang :"Inställning av språk ",
            UseLang :"Använd språk ",
            SetPBR_Set1 :"Registrera uppspelningshastighet 1 ",
            SetPBR_Set2 :"Registrera uppspelningshastighet 2 ",
            SetPBR_def :"Utgångsvärde för uppspelningshastighet ",
            SetPBR_step :"Uppspelningshastighetens ökning ",
            SetPBR_max :"Maximal uppspelningshastighet ",
            SetPBR_min :"Minsta uppspelningshastighet ",
            SetVol :"Ställ in volymen ",
            SetRewind_L :"Spola tillbaka (stor ",
            SetRewind_S :"Spola tillbaka (liten) ",
            SetForward_S :"Snabbspolning (liten) ",
            SetForward_L :"Snabb framåt (stor) ",
            MediaPlayer :"Mediaspelare ",
            History :"Historia ",
            Setting :"Inställning av ",
            OpenMedia :"Öppna media ",
            Clear :"Rensa ",
            Reload :"Ladda om ",
            DnD_Here :"Dra och släpp media här ",
            Favorite :"Favorit ",
            Delete :"Ta bort ",
            FullScreen :"Fullskärm ",
            Hide :"Dölj ",
            Delete_Dia_title:'Radera spårinformation',
            Delete_Dia_info:'Är du säker på att du vill radera den? Det går inte att återställa raderad spårinformation.',
            OK:'Ja',
            Cancel:'Avbryt',
        },
        es: {
            VolUp: 'Arriba',
            VolDown: 'Abajo',
            PlaybackTime: 'Tiempo de reproducción',
            Patron_message_ON: 'Mostrar mensaje',
            Patron:'Patrón',
            Rewind:"Rebobinar",
            Forward :"Adelante",
            Mini :"Minirreproductor",
            SwitchColumn_2 :"Cambiar a 2 columnas",
            SwitchColumn_1 :"Cambiar a 1 columna",
            RestoreWindow :"Restaurar ventana",
            Previous :"Anterior",
            Next :"Siguiente",
            PBR_Reduce :"Reducir la velocidad de reproducción",
            PBR_Set_1 :"Ajustar la velocidad de reproducción 1",
            PBR_Set_2 :"Establecer la velocidad de reproducción 2",
            PBR_Add :"Aumentar la velocidad de reproducción",
            Reset :"Restablecer",
            Pause :"Pausa",
            Play :"Reproducir",
            Shuffle :"Aleatorio",
            Repeat :"Repetir",
            Mute :"Silenciar",
            Fold :"Doblar",
            Extend :"Ampliar",
            Title :"Título",
            Count :"Contar",
            Date :"Último día reproducido",
            Edlapsed :"Días transcurridos",
            OpenMedia :"Abrir medios",
            Setting :"Configuración",
            Lang :"Idioma",
            PBR :"Velocidad de reproducción'",
            Vol :"Volumen",
            Time :"Control de tiempo",
            SetLang :"Ajuste del idioma",
            UseLang :"Utilizar el idioma",
            SetPBR_Set1 :"Registro de la velocidad de reproducción 1",
            SetPBR_Set2 :"Registrar la velocidad de reproducción 2",
            SetPBR_def :"Valor inicial de la velocidad de reproducción",
            SetPBR_step :"Incrementos de la velocidad de reproducción",
            SetPBR_max :"Velocidad máxima de reproducción",
            SetPBR_min :"Velocidad mínima de reproducción",
            SetVol :"Ajustar el volumen",
            SetRewind_L :"Rebobinar (grande)",
            SetRewind_S :"Rebobinar (pequeño)",
            SetForward_S :"Avance rápido (pequeño)",
            SetForward_L :"Avance rápido (grande)",
            MediaPlayer :"Reproductor multimedia",
            History :"Historia",
            Setting :"Configuración de",
            OpenMedia :"Abrir medios",
            Clear :"Borrar",
            Reload :"Recargar",
            DnD_Here :"Arrastrar y soltar medios aquí",
            Favorite :"Favorito",
            Delete :"Borrar",
            FullScreen :"Pantalla completa",
            Hide :"Ocultar",
            Delete_Dia_title:'Borrar la información de la pista',
            Delete_Dia_info:'¿Estás seguro de que quieres borrarla? La información de la pista borrada no se puede restaurar.',
            OK:'Sí',
            Cancel:'Cancelar',
        },
        sk: {
            VolUp: 'Nahor',
            VolDown: 'Dole',
            PlaybackTime: 'Čas prehrávania',
            Patron_message_ON: 'Zobraziť správu',
            Patron:'Patrón',
            Rewind:"Prevíjanie",
            Forward :"Dopredu",
            Mini :"Mini prehrávač",
            SwitchColumn_2 :"Prepnutie na 2 stĺpce",
            SwitchColumn_1 :"Prepnutie na 1 stĺpec",
            RestoreWindow :"Obnoviť okno",
            Previous :"Predchádzajúce",
            Next :"Ďalšie",
            PBR_Reduce :"Zníženie rýchlosti prehrávania",
            PBR_Set_1 :"Nastavenie na rýchlosť prehrávania 1",
            PBR_Set_2 :"Nastavenie na rýchlosť prehrávania 2",
            PBR_Add :"Zvýšiť rýchlosť prehrávania",
            Reset :"Obnoviť",
            Pause :"Pozastavenie",
            Play :"Prehrávanie",
            Shuffle :"Náhodné prehrávanie",
            Repeat :"Opakovať",
            Mute :"Mute",
            Fold :"Zložiť",
            Extend :"Rozšírenie",
            Title :"Názov",
            Count :"Count",
            Date :"Posledný prehrávaný deň",
            Edlapsed :"Uplynulé dni",
            OpenMedia :"Otvorené médiá",
            Setting :"Nastavenie",
            Lang :"Jazyk",
            PBR :"Rýchlosť prehrávania",
            Vol :"Hlasitosť",
            Time :"Ovládanie času",
            SetLang :"Nastavenie jazyka",
            UseLang :"Používanie jazyka",
            SetPBR_Set1 :"Registrácia rýchlosti prehrávania 1",
            SetPBR_Set2 :"Zaregistrovať rýchlosť prehrávania 2",
            SetPBR_def :"Počiatočná hodnota rýchlosti prehrávania",
            SetPBR_step :"Prírastky rýchlosti prehrávania",
            SetPBR_max :"Maximálna rýchlosť prehrávania",
            SetPBR_min :"Minimálna rýchlosť prehrávania",
            SetVol :"Nastavenie hlasitosti",
            SetRewind_L :"Prevíjanie dozadu (veľké",
            SetRewind_S :"Prevíjanie dozadu (malé)",
            SetForward_S :"Rýchle prevíjanie dopredu (malé)",
            SetForward_L :"Rýchle prevíjanie dopredu (veľké)",
            MediaPlayer :"Prehrávač médií",
            History :"História",
            Setting :"Nastavenie",
            OpenMedia :"Otvoriť médiá",
            Clear :"Vymazať",
            Reload :"Znovu načítať",
            DnD_Here :"Presuňte sem médiá",
            Favorite :"Obľúbené",
            Delete :"Odstrániť",
            FullScreen :"Na celú obrazovku",
            Hide :"Skryť",
            Delete_Dia_title:'Odstránenie informácií o trati',
            Delete_Dia_info:'Ste si istí, že ju chcete vymazať? Vymazané informácie o skladbe sa nedajú obnoviť.',
            OK:'Áno',
            Cancel:'Zrušiť',
        },
        sl: {
            VolUp: 'Navzgor',
            VolDown: 'Navzdol',
            PlaybackTime: 'Čas predvajanja',
            Patron_message_ON: 'Prikaži sporočilo',
            Patron:'Patron',
            Rewind:"Previjanje",
            Forward :"Naprej",
            Mini :"Mini predvajalnik",
            SwitchColumn_2 :"Preklop na 2 stolpca",
            SwitchColumn_1 :"Preklop na 1 stolpec",
            RestoreWindow :"Obnovitev okna",
            Previous :"Prejšnji",
            Next :"Naslednji",
            PBR_Reduce :"Zmanjšanje hitrosti predvajanja",
            PBR_Set_1 :"Nastavite na hitrost predvajanja 1",
            PBR_Set_2 :"Nastavitev na hitrost predvajanja 2",
            PBR_Add :"Povečanje hitrosti predvajanja",
            Reset :"Ponastavitev",
            Pause :"Zaustavitev",
            Play :"Predvajanje",
            Shuffle :"Premikanje (Shuffle)",
            Repeat :"Ponavljanje",
            Mute :"Izklop mikrofona",
            Fold :"Zložite",
            Extend :"Podaljšanje",
            Title :"Naslov",
            Count :"Count",
            Date :"Dan zadnjega predvajanja",
            Edlapsed :"Pretekli dnevi",
            OpenMedia :"Odprti mediji",
            Setting :"Nastavitev",
            Lang :"Jezik",
            PBR :"Hitrost predvajanja'",
            Vol :"Glasnost",
            Time :"Upravljanje časa",
            SetLang :"Nastavitev jezika",
            UseLang :"Uporaba jezika",
            SetPBR_Set1 :"Registracija hitrosti predvajanja 1",
            SetPBR_Set2 :"Registracija hitrosti predvajanja 2",
            SetPBR_def :"Začetna vrednost hitrosti predvajanja",
            SetPBR_step :"Povečanje hitrosti predvajanja",
            SetPBR_max :"Največja hitrost predvajanja",
            SetPBR_min :"Najmanjša hitrost predvajanja",
            SetVol :"Nastavitev glasnosti",
            SetRewind_L :"Previjanje nazaj (veliko",
            SetRewind_S :"Previjanje nazaj (majhno)",
            SetForward_S :"Hitro naprej (majhno)",
            SetForward_L :"Hitro naprej (veliko)",
            MediaPlayer :"Medijski predvajalnik",
            History :"Zgodovina",
            Setting :"Nastavitev",
            OpenMedia :"Odpiranje medijev",
            Clear :"Izbriši",
            Reload :"Ponovno nalaganje",
            DnD_Here :"Povlecite in spustite medije sem",
            Favorite :"Najljubši",
            Delete :"Izbriši",
            FullScreen :"Celozaslonsko",
            Hide :"Skrij",
            Delete_Dia_title:'Brisanje informacij o skladbi',
            Delete_Dia_info:'Ste prepričani, da želite izbrisati podatke? Izbrisanih informacij o skladbi ni mogoče obnoviti.',
            OK:'Da',
            Cancel:'Prekliči',
        },
        cs: {
            VolUp: 'Nahoru',
            VolDown: 'Dolů',
            PlaybackTime: 'Doba přehrávání',
            Patron_message_ON: 'Zobrazit zprávu',
            Patron:'Patron',
            Rewind:"Přetáčení",
            Forward :"Vpřed",
            Mini :"Mini přehrávač",
            SwitchColumn_2 :"Přepnutí na 2 sloupce",
            SwitchColumn_1 :"Přepnutí na 1 sloupec",
            RestoreWindow :"Obnovit okno",
            Previous :"Předchozí",
            Next :"Další",
            PBR_Reduce :"Snížení rychlosti přehrávání",
            PBR_Set_1 :"Nastavení rychlosti přehrávání 1",
            PBR_Set_2 :"Nastavení rychlosti přehrávání 2",
            PBR_Add :"Zvýšit rychlost přehrávání",
            Reset :"Obnovit",
            Pause :"Pozastavit",
            Play :"Přehrávání",
            Shuffle :"Náhodné přehrávání",
            Repeat :"Opakování",
            Mute :"Ztlumit",
            Fold :"Složit",
            Extend :"Rozšíření",
            Title :"Název",
            Count :"Count",
            Date :"Poslední přehraný den",
            Edlapsed :"Uplynulé dny",
            OpenMedia :"Otevřená média",
            Setting :"Nastavení",
            Lang :"Jazyk",
            PBR :"Rychlost přehrávání'",
            Vol :"Hlasitost",
            Time :"Ovládání času",
            SetLang :"Nastavení jazyka",
            UseLang :"Použití jazyka",
            SetPBR_Set1 :"Registrace rychlosti přehrávání 1",
            SetPBR_Set2 :"Registrace rychlosti přehrávání 2",
            SetPBR_def :"Počáteční hodnota rychlosti přehrávání",
            SetPBR_step :"Přírůstky rychlosti přehrávání",
            SetPBR_max :"Maximální rychlost přehrávání",
            SetPBR_min :"Minimální rychlost přehrávání",
            SetVol :"Nastavení hlasitosti",
            SetRewind_L :"Převíjení zpět (velké",
            SetRewind_S :"Převíjení zpět (malé)",
            SetForward_S :"Rychlé převíjení vpřed (malé)",
            SetForward_L :"Rychlé převíjení vpřed (velké)",
            MediaPlayer :"Přehrávač médií",
            History :"Historie",
            Setting :"Nastavení",
            OpenMedia :"Otevřít média",
            Clear :"Vymazat",
            Reload :"Znovu načíst",
            DnD_Here :"Přetáhněte média sem",
            Favorite :"Oblíbené",
            Delete :"Odstranit",
            FullScreen :"Na celou obrazovku",
            Hide :"Skrýt",
            Delete_Dia_title:'Odstranění informací o trati',
            Delete_Dia_info:'Určitě je chcete smazat? Smazané informace o skladbě nelze obnovit.',
            OK:'Ano',
            Cancel:'Zrušit',
        },
        da: {
            VolUp: 'Op',
            VolDown: 'Ned',
            PlaybackTime: 'Afspilningstid',
            Patron_message_ON: 'Vis besked',
            Patron:'Protektor',
            Rewind:"Spol tilbage",
            Forward :"Fremad",
            Mini :"Mini afspiller",
            SwitchColumn_2 :"Skift til 2 kolonner",
            SwitchColumn_1 :"Skift til 1 kolonne",
            RestoreWindow :"Gendan vindue",
            Previous :"Forrige",
            Next :"Næste",
            PBR_Reduce :"Reducer afspilningshastighed",
            PBR_Set_1 :"Indstil til afspilningshastighed 1",
            PBR_Set_2 :"Indstil til afspilningshastighed 2",
            PBR_Add :"Forøg afspilningshastigheden",
            Reset :"Nulstil",
            Pause :"Pause",
            Play :"Afspilning",
            Shuffle :"Shuffle",
            Repeat :"Gentag",
            Mute :"Mute",
            Fold :"Fold",
            Extend :"Forlæng",
            Title :"Titel",
            Count :"Count",
            Date :"Sidst afspillet dag",
            Edlapsed :"Forløbne dage",
            OpenMedia :"Åbn medier",
            Setting :"Indstilling",
            Lang :"Sprog",
            PBR :"Afspilningshastighed'",
            Vol :"Lydstyrke",
            Time :"Tidskontrol",
            SetLang :"Indstilling af sprog",
            UseLang :"Brug sprog",
            SetPBR_Set1 :"Registrer afspilningshastighed 1",
            SetPBR_Set2 :"Registrer afspilningshastighed 2",
            SetPBR_def :"Oprindelig værdi for afspilningshastighed",
            SetPBR_step :"Stigninger i afspilningshastighed",
            SetPBR_max :"Maksimal afspilningshastighed",
            SetPBR_min :"Mindste afspilningshastighed",
            SetVol :"Indstille lydstyrke",
            SetRewind_L :"Spol tilbage (stor",
            SetRewind_S :"Spol tilbage (lille)",
            SetForward_S :"Hurtigt fremad (lille)",
            SetForward_L :"Hurtig fremad (stor)",
            MediaPlayer :"Medieafspiller",
            History :"Historie",
            Setting :"Indstilling",
            OpenMedia :"Åbn medier",
            Clear :"Ryd",
            Reload :"Genindlæs",
            DnD_Here :"Træk og slip medier her",
            Favorite :"Favorit",
            Delete :"Slet",
            FullScreen :"Fuld skærm",
            Hide :"Skjul",
            Delete_Dia_title:'Slet sporoplysninger',
            Delete_Dia_info:'Er du sikker på, at du vil slette den? Slettede sporoplysninger kan ikke gendannes.',
            OK:'Ja',
            Cancel:'Annuller',
        },
        de: {
            VolUp: 'Auf',
            VolDown: 'Ab',
            PlaybackTime: 'Wiedergabedauer',
            Patron_message_ON: 'Nachricht anzeigen',
            Patron:'Schirmherr',
            Rewind:"Zurückspulen",
            Forward :"Vorwärts",
            Mini :"Mini-Spieler",
            SwitchColumn_2 :"Umschalten auf 2 Spalten",
            SwitchColumn_1 :"Umschalten auf 1 Spalte",
            RestoreWindow :"Fenster wiederherstellen",
            Previous :"Vorherige",
            Next :"Weiter",
            PBR_Reduce :"Abspielgeschwindigkeit verkleinern",
            PBR_Set_1 :"Auf Abspielgeschwindigkeit 1 setzen",
            PBR_Set_2 :"Auf Wiedergabegeschwindigkeit 2 setzen",
            PBR_Add :"Abspielgeschwindigkeit erhöhen",
            Reset :"Zurücksetzen",
            Pause :"Pause",
            Play :"Wiedergabe",
            Shuffle :"Zufallswiedergabe",
            Repeat :"Wiederholen",
            Mute :"Stummschalten",
            Fold :"Umklappen",
            Extend :"Erweitern",
            Title :"Titel",
            Count :"Zählen",
            Date :"Zuletzt gespielter Tag",
            Edlapsed :"Verstrichene Tage",
            OpenMedia :"Medien öffnen",
            Setting :"Einstellung",
            Lang :"Sprache",
            PBR :"Wiedergabegeschwindigkeit'",
            Vol :"Lautstärke",
            Time :"Zeitsteuerung",
            SetLang :"Einstellung der Sprache",
            UseLang :"Sprache verwenden",
            SetPBR_Set1 :"Wiedergabegeschwindigkeit 1 registrieren",
            SetPBR_Set2 :"Register Wiedergabegeschwindigkeit 2",
            SetPBR_def :"Anfangswert der Wiedergabegeschwindigkeit",
            SetPBR_step :"Inkremente der Wiedergabegeschwindigkeit",
            SetPBR_max :"Maximale Wiedergabegeschwindigkeit",
            SetPBR_min :"Minimale Wiedergabegeschwindigkeit",
            SetVol :"Lautstärke einstellen",
            SetRewind_L :"Rücklauf (groß)",
            SetRewind_S :"Rücklauf (klein)",
            SetForward_S :"Schneller Vorlauf (klein)",
            SetForward_L :"Schneller Vorlauf (groß)",
            MediaPlayer :"Media-Player",
            History :"Verlauf",
            Setting :"Einstellung",
            OpenMedia :"Medien öffnen",
            Clear :"Löschen",
            Reload :"Neu laden",
            DnD_Here :"Medien hierher ziehen und ablegen",
            Favorite :"Favorisieren",
            Delete :"Löschen",
            FullScreen :"Vollbild",
            Hide :"Ausblenden",
            Delete_Dia_title:'Trackinformationen löschen',
            Delete_Dia_info:'Sind Sie sicher, dass Sie sie löschen wollen? Gelöschte Titelinformationen können nicht wiederhergestellt werden.',
            OK:'Ja',
            Cancel:'Abbrechen',
        },
        hu: {
            VolUp: 'Fel',
            VolDown: 'Le',
            PlaybackTime: 'Lejátszási idő',
            Patron_message_ON: 'Üzenet megjelenítése',
            Patron:'Védnök',
            Rewind:"Visszatekerés",
            Forward :"Előre",
            Mini :"Mini lejátszó",
            SwitchColumn_2 :"Váltás 2 oszlopra",
            SwitchColumn_1 :"Váltás 1 oszlopra",
            RestoreWindow :"Ablak visszaállítása",
            Previous :"Előző",
            Next :"Következő",
            PBR_Reduce :"Lejátszási sebesség csökkentése",
            PBR_Set_1 :"Lejátszási sebesség 1-re állítása",
            PBR_Set_2 :"2. lejátszási sebesség beállítása",
            PBR_Add :"Lejátszási sebesség növelése",
            Reset :"Visszaállítása",
            Pause :"Szünet",
            Play :"Lejátszás",
            Shuffle :"Shuffle",
            Repeat :"Ismétlés",
            Mute :"Mute",
            Fold :"Összecsukható",
            Extend :"Extend",
            Title :"Cím",
            Count :"Count",
            Date :"Utoljára lejátszott nap",
            Edlapsed :"Lejárt napok",
            OpenMedia :"Média megnyitása",
            Setting :"Beállítás",
            Lang :"Nyelv",
            PBR :"Lejátszási sebesség'",
            Vol :"Hangerő",
            Time :"Időszabályozás",
            SetLang :"Nyelvi beállítás",
            UseLang :"Nyelv használata",
            SetPBR_Set1 :"Lejátszási sebesség regisztrálása 1",
            SetPBR_Set2 :"Lejátszási sebesség regisztrálása 2",
            SetPBR_def :"A lejátszási sebesség kezdeti értéke",
            SetPBR_step :"A lejátszási sebesség növekményei",
            SetPBR_max :"Maximális lejátszási sebesség",
            SetPBR_min :"Minimális lejátszási sebesség",
            SetVol :"Hangerő beállítása",
            SetRewind_L :"Visszatekerés (nagy",
            SetRewind_S :"Visszatekerés (kicsi)",
            SetForward_S :"Gyors előretekerés (kicsi)",
            SetForward_L :"Gyors előre (nagy)",
            MediaPlayer :"Médialejátszó",
            History :"Előzmények",
            Setting :"Beállítás",
            OpenMedia :"Média megnyitása",
            Clear :"Törlés",
            Reload :"Újratöltés",
            DnD_Here :"Húzza ide a médiát",
            Favorite :"Kedvenc",
            Delete :"Törlés",
            FullScreen :"Teljes képernyő",
            Hide :"Elrejteni",
            Delete_Dia_title:'Pálya információ törlése',
            Delete_Dia_info:'Biztos, hogy törölni szeretné? A törölt sávinformációk nem állíthatók vissza.',
            OK:'Igen',
            Cancel:'Cancel',
        },
        fi: {
            VolUp: 'Ylös',
            VolDown: 'Alas',
            PlaybackTime: 'Toistoaika',
            Patron_message_ON: 'Näytä viesti',
            Patron:'Patron',
            Rewind:"Kelaa taaksepäin",
            Forward :"Eteenpäin",
            Mini :"Mini-soitin",
            SwitchColumn_2 :"Vaihda 2 sarakkeeseen",
            SwitchColumn_1 :"Vaihda 1 sarakkeeseen",
            RestoreWindow :"Palauta ikkuna",
            Previous :"Edellinen",
            Next :"Seuraava",
            PBR_Reduce :"Vähennä toistonopeutta",
            PBR_Set_1 :"Aseta toistonopeudeksi 1",
            PBR_Set_2 :"Aseta toistonopeus 2",
            PBR_Add :"Lisää toistonopeutta",
            Reset :"Nollaa",
            Pause :"Pysäytä",
            Play :"Toista",
            Shuffle :"Sekoittaminen",
            Repeat :"Toista",
            Mute :"Mykistä",
            Fold :"Taita",
            Extend :"Extend",
            Title :"Otsikko",
            Count :"Count",
            Date :"Viimeksi soitettu päivä",
            Edlapsed :"Kuluneet päivät",
            OpenMedia :"Avaa Media",
            Setting :"Asetukset",
            Lang :"Kieli",
            PBR :"Toistonopeus'",
            Vol :"Äänenvoimakkuus",
            Time :"Ajan säätö",
            SetLang :"Kielen asetus",
            UseLang :"Käytä kieltä",
            SetPBR_Set1 :"Rekisteröi toistonopeus 1",
            SetPBR_Set2 :"Rekisteröi toistonopeus 2",
            SetPBR_def :"Toistonopeuden alkuarvo",
            SetPBR_step :"Toistonopeuden lisäykset",
            SetPBR_max :"Suurin toistonopeus",
            SetPBR_min :"Pienin toistonopeus",
            SetVol :"Äänenvoimakkuuden asettaminen",
            SetRewind_L :"Kelaus (suuri",
            SetRewind_S :"Kelaus (pieni)",
            SetForward_S :"Pikakelaus eteenpäin (pieni)",
            SetForward_L :"Pikakelaus eteenpäin (suuri)",
            MediaPlayer :"Mediasoitin",
            History :"Historia",
            Setting :"Asetukset",
            OpenMedia :"Avaa Media",
            Clear :"Tyhjennä",
            Reload :"Lataa uudelleen",
            DnD_Here :"Vedä ja pudota media tänne",
            Favorite :"Suosikki",
            Delete :"Poista",
            FullScreen :"Koko näyttö",
            Hide :"Piilota",
            Delete_Dia_title:'Poista kappaleen tiedot',
            Delete_Dia_info:'Haluatko varmasti poistaa sen? Poistettuja raitatietoja ei voi palauttaa.',
            OK:'Kyllä',
            Cancel:'Peruuta',
        },
        fr: {
            VolUp: 'Haut',
            VolDown: 'Bas',
            PlaybackTime: 'Temps de lecture',
            Patron_message_ON: 'Afficher le message',
            Patron:'Mécène',
            Rewind:"Rembobinage",
            Forward :"Avance",
            Mini :"Mini lecteur",
            SwitchColumn_2 :"Passer à 2 colonnes",
            SwitchColumn_1 :"Passer à 1 colonne",
            RestoreWindow :"Restaurer la fenêtre",
            Previous :"Précédent",
            Next :"Suivant",
            PBR_Reduce :"Réduire la vitesse de lecture",
            PBR_Set_1 :"Régler sur la vitesse de lecture 1",
            PBR_Set_2 :"Régler sur la vitesse de lecture 2",
            PBR_Add :"Augmenter la vitesse de lecture",
            Reset :"Réinitialiser",
            Pause :"Pause",
            Play :"Lecture",
            Shuffle :"Aléatoire",
            Repeat :"Répétition",
            Mute :"Muet",
            Fold :"Plier",
            Extend :"Déployer",
            Title :"Titre",
            Count :"Compte",
            Date :"Dernier jour de lecture",
            Edlapsed :"Jours écoulés",
            OpenMedia :"Ouvrir le média",
            Setting :"Réglage de",
            Lang :"Langue",
            PBR :"Vitesse de lecture",
            Vol :"Volume",
            Time :"Contrôle du temps",
            SetLang :"Réglage de la langue",
            UseLang :"Utiliser la langue",
            SetPBR_Set1 :"Enregistrer la vitesse de lecture 1",
            SetPBR_Set2 :"Enregistrer la vitesse de lecture 2",
            SetPBR_def :"Valeur initiale de la vitesse de lecture",
            SetPBR_step :"Incréments de la vitesse de lecture",
            SetPBR_max :"Vitesse de lecture maximale",
            SetPBR_min :"Vitesse de lecture minimale",
            SetVol :"Régler le volume",
            SetRewind_L :"Rembobinage (grand)",
            SetRewind_S :"Rembobinage (petit)",
            SetForward_S :"Avance rapide (petit)",
            SetForward_L :"Avance rapide (grand)",
            MediaPlayer :"Lecteur multimédia",
            History :"Historique",
            Setting :"Réglage de",
            OpenMedia :"Ouvrir le média",
            Clear :"Effacer",
            Reload :"Recharger",
            DnD_Here :"Glisser et déposer les médias ici",
            Favorite :"Favoris",
            Delete :"Supprimer",
            FullScreen :"Plein écran",
            Hide :"Cacher",
            Delete_Dia_title:'Supprimer les informations sur la piste',
            Delete_Dia_info:'Êtes-vous sûr de vouloir les supprimer ? Les informations de piste supprimées ne peuvent pas être restaurées.',
            OK:'Oui',
            Cancel:'Annuler',
        },
        bg: {
            VolUp: 'Нагоре',
            VolDown: 'надолу',
            PlaybackTime: 'Време за възпроизвеждане',
            Patron_message_ON: 'Покажи съобщение',
            Patron:'Патрон',
            Rewind:"Пренавиване",
            Forward :"Напред",
            Mini :"Мини плейър",
            SwitchColumn_2 :"Превключване към 2 колони",
            SwitchColumn_1 :"Превключване към 1 колона",
            RestoreWindow :"Възстановяване на прозореца",
            Previous :"Предишен",
            Next :"Следваща",
            PBR_Reduce :"Намаляване на скоростта на възпроизвеждане",
            PBR_Set_1 :"Настройте скоростта на възпроизвеждане на 1",
            PBR_Set_2 :"Задаване на скорост на възпроизвеждане 2",
            PBR_Add :"Увеличаване на скоростта на възпроизвеждане",
            Reset :"Нулиране на",
            Pause :"Пауза",
            Play :"Възпроизвеждане",
            Shuffle :"Разбъркване",
            Repeat :"Повтаряне",
            Mute :"Заглушаване на звука",
            Fold :"Сгънете",
            Extend :"Разширяване",
            Title :"Заглавие",
            Count :"Брой",
            Date :"Последно изигран ден",
            Edlapsed :"Изтекли дни",
            OpenMedia :"Отваряне на медия",
            Setting :"Настройка на",
            Lang :"Език",
            PBR :"Скорост на възпроизвеждане",
            Vol :"Сила на звука",
            Time :"Управление на времето",
            SetLang :"Настройка на езика",
            UseLang :"Използване на езика",
            SetPBR_Set1 :"Регистриране на скоростта на възпроизвеждане 1",
            SetPBR_Set2 :"Регистриране на скоростта на възпроизвеждане 2",
            SetPBR_def :"Първоначална стойност на скоростта на възпроизвеждане",
            SetPBR_step :"Увеличения на скоростта на възпроизвеждане",
            SetPBR_max :"Максимална скорост на възпроизвеждане",
            SetPBR_min :"Минимална скорост на възпроизвеждане",
            SetVol :"Задаване на силата на звука",
            SetRewind_L :"Превъртане назад (голямо",
            SetRewind_S :"Превъртане назад (малко)",
            SetForward_S :"Бързо превъртане напред (малко)",
            SetForward_L :"Бързо превъртане напред (голямо)",
            MediaPlayer :"Медиен плейър",
            History :"История",
            Setting :"Настройка на",
            OpenMedia :"Отваряне на медия",
            Clear :"Изчистване на",
            Reload :"Презареждане",
            DnD_Here :"Влачете и пуснете медия тук",
            Favorite :"Любими",
            Delete :"Изтриване",
            FullScreen :"Пълен екран",
            Hide :"Скриване на",
            Delete_Dia_title:'Изтриване на информация за песента',
            Delete_Dia_info:'Сигурни ли сте, че искате да я изтриете? Изтритата информация за песни не може да бъде възстановена.',
            OK:'Да',
            Cancel:'Отмяна на',
        },
        pl: {
            VolUp: 'Góra',
            VolDown: 'Dół',
            PlaybackTime: 'Czas odtwarzania',
            Patron_message_ON: 'Pokaż wiadomość',
            Patron:'Patron',
            Rewind:"Przewiń do tyłu",
            Forward :"Do przodu",
            Mini :"Mini odtwarzacz",
            SwitchColumn_2 :"Przełączanie na 2 kolumny",
            SwitchColumn_1 :"Przełącz na 1 kolumnę",
            RestoreWindow :"Przywróć okno",
            Previous :"Poprzedni",
            Next :"Następny",
            PBR_Reduce :"Zmniejsz prędkość odtwarzania",
            PBR_Set_1 :"Ustaw na prędkość odtwarzania 1",
            PBR_Set_2 :"Ustaw prędkość odtwarzania 2",
            PBR_Add :"Zwiększ prędkość odtwarzania",
            Reset :"Resetuj",
            Pause :"Wstrzymaj",
            Play :"Odtwarzanie",
            Shuffle :"Shuffle",
            Repeat :"Powtarzaj",
            Mute :"Wycisz",
            Fold :"Składanie",
            Extend :"Rozwiń",
            Title :"Tytuł",
            Count :"Count",
            Date :"Ostatnio odtwarzany dzień",
            Edlapsed :"Dni, które upłynęły",
            OpenMedia :"Otwórz Media",
            Setting :"Ustawienia",
            Lang :"Język",
            PBR :"Prędkość odtwarzania",
            Vol :"Głośność",
            Time :"Regulacja czasu",
            SetLang :"Ustawianie języka",
            UseLang :"Użyj języka",
            SetPBR_Set1 :"Rejestrowanie prędkości odtwarzania 1",
            SetPBR_Set2 :"Rejestrowanie prędkości odtwarzania 2",
            SetPBR_def :"Wartość początkowa prędkości odtwarzania",
            SetPBR_step :"Przyrosty prędkości odtwarzania",
            SetPBR_max :"Maksymalna prędkość odtwarzania",
            SetPBR_min :"Minimalna prędkość odtwarzania",
            SetVol :"Ustawianie głośności",
            SetRewind_L :"Przewijanie do tyłu (duże)",
            SetRewind_S :"Przewijanie do tyłu (małe)",
            SetForward_S :"Szybkie przewijanie do przodu (małe)",
            SetForward_L :"Szybkie przewijanie do przodu (duże)",
            MediaPlayer :"Odtwarzacz multimedialny",
            History :"Historia",
            Setting :"Ustawianie",
            OpenMedia :"Otwórz Media",
            Clear :"Wyczyść",
            Reload :"Przeładuj",
            DnD_Here :"Przeciągnij i upuść media tutaj",
            Favorite :"Ulubione",
            Delete :"Usuń",
            FullScreen :"FullScreen",
            Hide :"Ukryj",
            Delete_Dia_title:'Usuń informacje o śladzie',
            Delete_Dia_info:'Czy na pewno chcesz je usunąć? Usuniętych informacji o ścieżce nie można przywrócić.',
            OK:'Tak',
            Cancel:'Anuluj',
        },
        pt: {
            VolUp: 'Acima',
            VolDown: 'Abaixo',
            PlaybackTime: 'Tempo de reprodução',
            Patron_message_ON: 'Mostrar mensagem',
            Patron:'Patrono',
            Rewind:"Rebobinar",
            Forward :"Avançar",
            Mini :"Mini Jogador",
            SwitchColumn_2 :"Mudar para 2 colunas",
            SwitchColumn_1 :"Mudar para 1 coluna",
            RestoreWindow :"Janela de restauro",
            Previous :"Anterior",
            Next :"Próximo",
            PBR_Reduce :"Reduzir a velocidade de reprodução",
            PBR_Set_1 :"Configurar para velocidade de reprodução 1",
            PBR_Set_2 :"Configurar para velocidade de reprodução 2",
            PBR_Add :"Aumentar a velocidade de reprodução",
            Reset :"Reinicialização",
            Pause :"Pausa",
            Play :"Reproduzir",
            Shuffle :"Baralhamento",
            Repeat :"Repita",
            Mute :"Mudo",
            Fold :"Dobrar",
            Extend :"Prolongar",
            Title :"Título",
            Count :"Conde",
            Date :"Último dia jogado",
            Edlapsed :"Dias decorridos",
            OpenMedia :"Meios de comunicação abertos",
            Setting :"Configuração",
            Lang :"Idioma",
            PBR :"Velocidade de reprodução''.",
            Vol :"Volume",
            Time :"Controlo do tempo",
            SetLang :"Definição do idioma",
            UseLang :"Usar Língua",
            SetPBR_Set1 :"Registar velocidade de reprodução 1",
            SetPBR_Set2 :"Registar velocidade de reprodução 2",
            SetPBR_def :"Valor inicial da velocidade de reprodução",
            SetPBR_step :"Incrementos de velocidade de reprodução",
            SetPBR_max :"Velocidade máxima de reprodução",
            SetPBR_min :"Velocidade mínima de reprodução",
            SetVol :"Volume definido",
            SetRewind_L :"Rebobinar (grande",
            SetRewind_S :"Rebobinar (pequeno)",
            SetForward_S :"Avanço rápido (pequeno)",
            SetForward_L :"Avanço Rápido (Grande)",
            MediaPlayer :"Leitor de mídia",
            History :"História",
            Setting :"Configuração",
            OpenMedia :"Meios de comunicação abertos",
            Clear :"Limpar",
            Reload :"Recarregar",
            DnD_Here :"Meios de arrastar e largar aqui",
            Favorite :"Favorito",
            Delete :"Eliminar",
            FullScreen :"FullScreen",
            Hide :"Esconder",
            Delete_Dia_title:'Eliminar informação de pista',
            Delete_Dia_info:'Tem a certeza de que o quer apagar? As informações de pista apagadas não podem ser restauradas.',
            OK:'Sim',
            Cancel:'Cancelar',
        },
        lv: {
            VolUp: 'Uz augšu',
            VolDown: 'Uz leju',
            PlaybackTime: 'Atskaņošanas laiks',
            Patron_message_ON: 'Rādīt ziņojumu',
            Patron:'Patrons',
            Rewind:"Atgriezt atpakaļ",
            Forward :"Uz priekšu",
            Mini :"Mini atskaņotājs",
            SwitchColumn_2 :"Pārslēgšanās uz 2 kolonnām",
            SwitchColumn_1 :"Pārslēgšanās uz 1 kolonnu",
            RestoreWindow :"Atjaunot logu",
            Previous :"Iepriekšējais",
            Next :"Nākamais",
            PBR_Reduce :"Samazināt atskaņošanas ātrumu",
            PBR_Set_1 :"Iestatiet atskaņošanas ātrumu 1",
            PBR_Set_2 :"Iestatīt atskaņošanas ātrumu 2",
            PBR_Add :"Palielināt atskaņošanas ātrumu",
            Reset :"Atiestatīt",
            Pause :"Apturēšana",
            Play :"Atskaņošana",
            Shuffle :"Izmaiņu atskaņošana",
            Repeat :"Atkārtot",
            Mute :"Izslēgt skaņu",
            Fold :"Salocīt",
            Extend :"Paplašināt",
            Title :"Nosaukums",
            Count :"Count",
            Date :"Pēdējā atskaņotā diena",
            Edlapsed :"Pagājušās dienas",
            OpenMedia :"Atvērt multivides",
            Setting :"Iestatīšana",
            Lang :"Valoda",
            PBR :"Atskaņošanas ātrums'",
            Vol :"Skaļums",
            Time :"Laika kontrole",
            SetLang :"Valodas iestatījums",
            UseLang :"Valodas lietošana",
            SetPBR_Set1 :"Reģistrēt atskaņošanas ātrumu 1",
            SetPBR_Set2 :"Reģistrēt atskaņošanas ātrumu 2",
            SetPBR_def :"Sākotnējā atskaņošanas ātruma vērtība",
            SetPBR_step :"Atskaņošanas ātruma pieaugums",
            SetPBR_max :"Maksimālais atskaņošanas ātrums",
            SetPBR_min :"Minimālais atskaņošanas ātrums",
            SetVol :"Skaļuma iestatīšana",
            SetRewind_L :"Atgriešana atpakaļ (liela",
            SetRewind_S :"Atgriešana atpakaļ (mazā)",
            SetForward_S :"Ātrā pārslēgšana uz priekšu (maza)",
            SetForward_L :"Ātrā virzība uz priekšu (liela)",
            MediaPlayer :"Multivides atskaņotājs",
            History :"Vēsture",
            Setting :"Iestatīšana",
            OpenMedia :"Atvērt multivides",
            Clear :"Notīrīt",
            Reload :"Pārlādēt",
            DnD_Here :"Velciet un nometiet multivides šeit",
            Favorite :"Iecienītākie",
            Delete :"Dzēst",
            FullScreen :"Pilna ekrāna",
            Hide :"Paslēpt",
            Delete_Dia_title:'Dzēst dziesmu informāciju',
            Delete_Dia_info:'Vai esat pārliecināts, ka vēlaties to dzēst? Izdzēstu dziesmas informāciju nevar atjaunot.',
            OK:'Jā',
            Cancel:'Atcelt',
        },
        lt: {
            VolUp: 'Aukštyn',
            VolDown: 'Žemyn',
            PlaybackTime: 'Atkūrimo laikas',
            Patron_message_ON: 'Rodyti pranešimą',
            Patron:'Mecenatas',
            Rewind:"Atsukimas atgal",
            Forward :"Pirmyn",
            Mini :"Mini grotuvas",
            SwitchColumn_2 :"Perjungimas į 2 stulpelius",
            SwitchColumn_1 :"Perjungimas į 1 stulpelį",
            RestoreWindow :"Atkurti langą",
            Previous :"Ankstesnis",
            Next :"Kitas",
            PBR_Reduce :"Sumažinti atkūrimo greitį",
            PBR_Set_1 :"Nustatykite atkūrimo greitį 1",
            PBR_Set_2 :"Nustatyti atkūrimo greitį 2",
            PBR_Add :"Padidinti atkūrimo greitį",
            Reset :"Iš naujo nustatyti",
            Pause :"Sustabdyti",
            Play :"Atkurti",
            Shuffle :"Shuffle",
            Repeat :"Kartoti",
            Mute :"Nutildyti garsą",
            Fold :"Sulenkite",
            Extend :"Išplėsti",
            Title :"Pavadinimas",
            Count :"Skaičius",
            Date :"Paskutinė grota diena",
            Edlapsed :"Praėjusios dienos",
            OpenMedia :"Atidaryti laikmeną",
            Setting :"Nustatymas",
            Lang :"Kalba",
            PBR :"Atkūrimo greitis'",
            Vol :"Garsumas",
            Time :"Laiko valdymas",
            SetLang :"Kalbos nustatymas",
            UseLang :"Naudoti kalbą",
            SetPBR_Set1 :"Registruoti atkūrimo greitį 1",
            SetPBR_Set2 :"Užregistruoti atkūrimo greitį 2",
            SetPBR_def :"Pradinė atkūrimo greičio vertė",
            SetPBR_step :"Atkūrimo greičio didinimas",
            SetPBR_max :"Didžiausias atkūrimo greitis",
            SetPBR_min :"Mažiausias atkūrimo greitis",
            SetVol :"Nustatyti garsumą",
            SetRewind_L :"Persukimas atgal (didelis",
            SetRewind_S :"Persukimas atgal (mažas)",
            SetForward_S :"Greitas persukimas pirmyn (mažas)",
            SetForward_L :"Greitas persukimas pirmyn (didelis)",
            MediaPlayer :"Medijos grotuvas",
            History :"Istorija",
            Setting :"Nustatymas",
            OpenMedia :"Atidaryti laikmeną",
            Clear :"Išvalyti",
            Reload :"Perkrauti",
            DnD_Here :"Vilkite ir nuleiskite mediją čia",
            Favorite :"Mėgstamiausia",
            Delete :"Ištrinti",
            FullScreen :"Viso ekrano",
            Hide :"Paslėpti",
            Delete_Dia_title:'Ištrinti kelio informaciją',
            Delete_Dia_info:'Ar tikrai norite ją ištrinti? Ištrinta takelio informacija negali būti atkurta.',
            OK:'Taip',
            Cancel:'Atšaukti',
        },
        ro: {
            VolUp: 'Sus',
            VolDown: 'Jos',
            PlaybackTime: 'Timp de redare',
            Patron_message_ON: 'Arată mesajul',
            Patron:'Patron',
            Rewind:"Derulare înapoi",
            Forward :"Înainte",
            Mini :"Mini player",
            SwitchColumn_2 :"Comutați la 2 coloane",
            SwitchColumn_1 :"Comutați la 1 coloană",
            RestoreWindow :"Fereastra de restaurare",
            Previous :"Anterior",
            Next :"Următorul",
            PBR_Reduce :"Reducerea vitezei de redare",
            PBR_Set_1 :"Setați viteza de redare 1",
            PBR_Set_2 :"Setați viteza de redare 2",
            PBR_Add :"Creșteți viteza de redare",
            Reset :"Resetați",
            Pause :"Pauză",
            Play :"Redare",
            Shuffle :"Shuffle",
            Repeat :"Repetare",
            Mute :"Mute",
            Fold :"Pliați",
            Extend :"Extindeți",
            Title :"Titlu",
            Count :"Numărătoare",
            Date :"Ultima zi de redare",
            Edlapsed :"Zilele scurse",
            OpenMedia :"Deschideți media",
            Setting :"Setarea",
            Lang :"Limba",
            PBR :"Viteză de redare'",
            Vol :"Volum",
            Time :"Controlul timpului",
            SetLang :"Setarea limbii",
            UseLang :"Utilizați limba",
            SetPBR_Set1 :"Înregistrați viteza de redare 1",
            SetPBR_Set2 :"Înregistrați viteza de redare 2",
            SetPBR_def :"Valoarea inițială a vitezei de redare",
            SetPBR_step :"Creșteri ale vitezei de redare",
            SetPBR_max :"Viteza maximă de redare",
            SetPBR_min :"Viteza minimă de redare",
            SetVol :"Setați volumul",
            SetRewind_L :"Derulare înapoi (mare",
            SetRewind_S :"Derulare înapoi (mică)",
            SetForward_S :"Avansare rapidă (mic)",
            SetForward_L :"Avansare rapidă (mare)",
            MediaPlayer :"Media Player",
            History :"Istoric",
            Setting :"Setare",
            OpenMedia :"Deschidere media",
            Clear :"Ștergeți",
            Reload :"Reîncărcați",
            DnD_Here :"Trageți și plasați mediile aici",
            Favorite :"Favorit",
            Delete :"Ștergeți",
            FullScreen :"Ecran complet",
            Hide :"Ascundeți",
            Delete_Dia_title:'Ștergeți informațiile despre piese',
            Delete_Dia_info:'Sunteți sigur că doriți să le ștergeți? Informațiile despre piese șterse nu pot fi restaurate.',
            OK:'Da',
            Cancel:'Anulare',
        },
        ru: {
            VolUp: 'Вверх',
            VolDown: 'Вниз',
            PlaybackTime: 'Время воспроизведения',
            Patron_message_ON: 'Показать сообщение',
            Patron:'Патрон',
            Rewind:"Перемотка",
            Forward :"Перемотка вперед",
            Mini :"Мини-плеер",
            SwitchColumn_2 :"Переключение на 2 колонки",
            SwitchColumn_1 :"Переключиться на 1 колонку",
            RestoreWindow :"Восстановить окно",
            Previous :"Предыдущий",
            Next :"Следующий",
            PBR_Reduce :"Уменьшить скорость воспроизведения",
            PBR_Set_1 :"Установите скорость воспроизведения 1",
            PBR_Set_2 :"Установите скорость воспроизведения 2",
            PBR_Add :"Увеличить скорость воспроизведения",
            Reset :"Сброс",
            Pause :"Приостановить",
            Play :"Воспроизведение",
            Shuffle :"Перемешать",
            Repeat :"Повтор",
            Mute :"Отключить звук",
            Fold :"Свернуть",
            Extend :"Развернуть",
            Title :"Заголовок",
            Count :"Счет",
            Date :"Последний воспроизведенный день",
            Edlapsed :"Прошедшие дни",
            OpenMedia :"Открыть медиа",
            Setting :"Настройка",
            Lang :"Язык",
            PBR :"Скорость воспроизведения'",
            Vol :"Громкость",
            Time :"Управление временем",
            SetLang :"Настройка языка",
            UseLang :"Использовать язык",
            SetPBR_Set1 :"Регистрация скорости воспроизведения 1",
            SetPBR_Set2 :"Регистрация скорости воспроизведения 2",
            SetPBR_def :"Начальное значение скорости воспроизведения",
            SetPBR_step :"Приращения скорости воспроизведения",
            SetPBR_max :"Максимальная скорость воспроизведения",
            SetPBR_min :"Минимальная скорость воспроизведения",
            SetVol :"Установить громкость",
            SetRewind_L :"Перемотка назад (большая",
            SetRewind_S :"Перемотка назад (маленькая)",
            SetForward_S :"Перемотка вперед (маленькая)",
            SetForward_L :"Перемотка вперед (большая)",
            MediaPlayer :"Медиаплеер",
            History :"История",
            Setting :"Настройка",
            OpenMedia :"Открыть медиа",
            Clear :"Очистить",
            Reload :"Перезагрузить",
            DnD_Here :"Перетащите медиа сюда",
            Favorite :"Избранное",
            Delete :"Удалить",
            FullScreen :"Полноэкранный режим",
            Hide :"Скрыть",
            Delete_Dia_title:'Удаление информации о треке',
            Delete_Dia_info:'Вы уверены, что хотите удалить ее? Удаленная информация о дорожке не может быть восстановлена.',
            OK:'Да',
            Cancel:'Отменить',
        },
        zh: {
            VolUp: '上',
            VolDown: '下',
            PlaybackTime: '播放时间',
            Patron_message_ON: '显示信息',
            Patron:'赞助人',
            Rewind:"倒退",
            Forward :"前进",
            Mini :"迷你播放器",
            SwitchColumn_2 :"切换到2栏",
            SwitchColumn_1 :"切换到1栏",
            RestoreWindow :"恢复窗口",
            Previous :"上一页",
            Next :"下一页",
            PBR_Reduce :"降低播放速度",
            PBR_Set_1 :"设置为播放速度1",
            PBR_Set_2 :"设置为播放速度2",
            PBR_Add :"提高播放速度",
            Reset :"重置",
            Pause :"暂停",
            Play :"播放",
            Shuffle :"洗牌",
            Repeat :"重复播放",
            Mute :"静音",
            Fold :"折叠",
            Extend :"延长",
            Title :"标题",
            Count :"统计数据",
            Date :"最后播放日",
            Edlapsed :"已过去的天数",
            OpenMedia :"打开媒体",
            Setting :"设置",
            Lang :"语言设置",
            PBR :"播放速度'。",
            Vol :"音量",
            Time :"时间控制",
            SetLang :"语言设置",
            UseLang :"使用语言",
            SetPBR_Set1 :"注册播放速度1",
            SetPBR_Set2 :"注册播放速度2",
            SetPBR_def :"播放速度的初始值",
            SetPBR_step :"播放速度增量",
            SetPBR_max :"最大播放速度",
            SetPBR_min :"最小播放速度",
            SetVol :"设置音量",
            SetRewind_L :"倒退（大",
            SetRewind_S :"倒退（小",
            SetForward_S :"快进（小",
            SetForward_L :"快进（大",
            MediaPlayer :"媒体播放器",
            History :"历史记录",
            Setting :"设置",
            OpenMedia :"打开媒体",
            Clear :"清除",
            Reload :"重新加载",
            DnD_Here :"在这里拖放媒体",
            Favorite :"收藏",
            Delete :"删除",
            FullScreen :"全屏",
            Hide :"隐藏",
            Delete_Dia_title:'删除轨道信息',
            Delete_Dia_info:'你确定要删除它吗？被删除的轨道信息不能被恢复。',
            OK:'是的',
            Cancel:'取消',
        },
    }

    // inclues 関数でブールレン型で指定の文字列が配列内にあるか
    const flag = locale_lists.includes(locale)
    if(flag){
        // console.log(flag)
        return (trans[locale][key])
        // return trans[String(locale)].String[key]
    }else{
        // console.log("Not Match")
        return trans["en"][key]
    }

}

